package:
  name: chemper
  version: "0.0.0"

source:
  path: ../..

build:
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - pytest
  imports:
    - chemper

about:
  home: https://github.com/MobleyLab/chemper
  license: MIT License
