name: chemper
channels:
    - omnia
    - openeye
    - rdkit
dependencies:
    - python>=3.5.2
    - numpy
    - openeye-toolkits
    - rdkit
    - networkx
    - numpydoc
    - pip
    - pip:
        - nbsphinx
